Repository atlp-rwanda/atlp-pulse-mobile, pull requests merged in 2024-09, with the labels that each got.

#25 ch(#13): Setup unit testing circle ci and coveralls badges
  .circleci/config.yml
  .coveralls.yml
  .gitignore
  __tests__/TabOneScreen-test.tsx
  __tests__/TabTwoScreen-test.tsx
  __tests__/__snapshots__/Layout.tsx.snap
  __tests__/__snapshots__/TabOneScreen-test.tsx.snap
  __tests__/__snapshots__/TabTwoScreen-test.tsx.snap
  __tests__/__snapshots__/TabTwoScreen.tsx.snap
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/(tabs)/two.tsx
  app/+html.tsx
  components/__tests__/StyledText-test.js
  package.json
  tailwind.config.js
  tsconfig.json
Labels: chore, ready for review

#23 Chore(#11): Setup GraphQL with Apollo
  app/(tabs)/_layout.tsx
  graphql/client.ts
  graphql/mutations/Attendance.tsx
  graphql/mutations/event.tsx
  graphql/mutations/help.mutation.tsx
  graphql/mutations/notificationMutation.tsx
  graphql/mutations/resetPassword.tsx
  graphql/queries/Attendance.tsx
  graphql/queries/NotificationMutation.tsx
  graphql/queries/User.tsx
  graphql/queries/event.tsx
  graphql/queries/tickets.queries.tsx
  package.json
Labels: chore, ready for review

#27 #19 Setup app theme
  __tests__/+not-found.test.tsx
  __tests__/TabOneScreen-test.tsx
  __tests__/TabTwoScreen-test.tsx
  __tests__/__snapshots__/Layout.tsx.snap
  __tests__/__snapshots__/TabOneScreen-test.tsx.snap
  __tests__/__snapshots__/TabTwoScreen-test.tsx.snap
  __tests__/__snapshots__/TabTwoScreen.tsx.snap
  __tests__/components/Themed.test.tsx
  __tests__/components/buttons.test.tsx
  app.d.ts
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/(tabs)/two.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/modal.tsx
  assets/fonts/SpaceMono-Regular.ttf
  babel.config.js
  components/EditScreenInfo.tsx
  components/ExternalLink.tsx
  components/StyledText.tsx
  components/buttons.tsx
  components/icons/icons.ts
  global.css
  metro.config.js
  package.json
  react-native.config.js
  tailwind.config.js
  tsconfig.json
Labels: chore, ready for review

#32 #28: Expo Setup
  app.json
  eas.json
  package.json
Labels: chore, ready for review

#29 #15 Eslint and Prettier configurations
  .circleci/config.yml
  .coveralls.yml
  .eslintrc.json
  .idea/.gitignore
  .idea/atlp-pulse-mobile.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .prettierrc
  __tests__/+not-found.test.tsx
  __tests__/components/Themed.test.tsx
  __tests__/components/buttons.test.tsx
  app.d.ts
  app.json
  app/+not-found.tsx
  app/_layout.tsx
  babel.config.js
  components/buttons.tsx
  components/icons/icons.ts
  eslint.config.mjs
  global.css
  graphql/mutations/notificationMutation.tsx
  graphql/mutations/resetPassword.tsx
  graphql/queries/Attendance.tsx
  graphql/queries/NotificationMutation.tsx
  graphql/queries/event.tsx
  metro.config.js
  package.json
  react-native.config.js
  tailwind.config.js
  tsconfig.json
Labels: ready for review

#26 #1 App onboarding
  .gitignore
  __tests__/onboarding/Onboarding.test.tsx
  app.json
  app/(onboarding)/_layout.tsx
  app/(onboarding)/index.tsx
  app/_layout.tsx
  assets/images/logo-dark.png
  assets/images/logo-light.png
  assets/images/onboarding/1.png
  assets/images/onboarding/2.png
  assets/images/onboarding/3.png
  components/Themed.tsx
  global.d.ts
  package.json
Labels: feature, ready for review

#33 #1 Fix text colors on onboarding screens
  app/(onboarding)/index.tsx
Labels: bug

#38 ft(#03): Login Implementation
  __tests__/Dashboard/index.test.tsx
  __tests__/Login/OrgLogin.test.tsx
  __tests__/Login/UserLogin.test.tsx
  __tests__/Trainee/index.test.tsx
  app/(onboarding)/index.tsx
  app/_layout.tsx
  app/auth/_layout.tsx
  app/auth/login.tsx
  app/dashboard/index.tsx
  app/index.tsx
  app/trainee/index.tsx
  assets/Icons/auth/Icons.tsx
  components/Login/OrgLogin.tsx
  components/Login/UserLogin.tsx
  graphql/client.ts
  graphql/mutations/login.mutation.ts
  hook/useAuth.tsx
  metro.config.js
  nativewind-env.d.ts
  package.json
  tsconfig.json
  validations/login.schema.ts
Labels: feature, ready for review
