Repository atlp-rwanda/atlp-pulse-mobile, pull requests merged in 2024-11, with the labels that each got.

#75 Fix Display Org login Error With Toast
  app/auth/login/index.tsx
  app/auth/register.tsx
  components/perfomanceStats/index.tsx
  components/sidebar.tsx
  components/sprintRatings.tsx
Labels: ready for review

#79 Fix Typographical Errors
  app/auth/forgot-password.tsx
  components/Login/UserLogin.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
Labels: ready for review

#81 Feature(#61): Trainee profile prefences/settings
  app/dashboard/_layout.tsx
  app/dashboard/trainee/preference.tsx
  components/LanguagePicker.tsx
  components/ProfileDropdown.tsx
  components/settingPreference/SettingPreference.tsx
  package-lock.json
  package.json
Labels: ready for review

#86 Localization Enhancements
  app/auth/forgot-password.tsx
  app/auth/login/index.tsx
  app/auth/register.tsx
  app/auth/reset-password.tsx
  app/dashboard/trainee/profile/edit.tsx
  app/dashboard/trainee/profile/index.tsx
  components/ProfileDropdown.tsx
  components/Resume.tsx
  components/perfomanceStats/index.tsx
  components/settingPreference/SettingPreference.tsx
  components/sidebar.tsx
  components/sprintRatings.tsx
  components/trainee/Account.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
Labels: ready for review

#85 ft (#73): implementation of Attendance Page
  app/dashboard/trainee/attendance.tsx
  assets/images/attend.png
  components/sidebar.tsx
  components/sprintRatings.tsx
  graphql/mutations/ratings.tsx
  graphql/queries/Attendance.tsx
  graphql/queries/rating.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: ready for review

#90 View All Event on calendar
  app/dashboard/calendar/index.tsx
  components/calendar/CalendarBody.tsx
  components/calendar/CalendarHeader.tsx
  components/calendar/CalendarSkeleton.tsx
  components/calendar/CustomButton.tsx
  components/calendar/DatePickerCard.tsx
  components/calendar/EventCard.tsx
  components/sidebar.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: ready for review

#97 Fix: expo app routing
  .env.example
  babel.config.js
  components/Resume.tsx
  package-lock.json
  package.json
Labels: bug

#96 Ft(#70): Performance Page Optimization
  app/dashboard/perfomance/index.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
Labels: ready for review

#91 Ft(#84): Fetch Trainee Notifications
  app/_layout.tsx
  app/dashboard/_layout.tsx
  app/dashboard/trainee/notifications.tsx
  app/dashboard/trainee/profile/index.tsx
  graphql/mutations/notificationMutation.tsx
  graphql/queries/NotificationMutation.tsx
  graphql/queries/Notifications.queries.tsx
  hooks/useAuth.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
  package.json
Labels: feature, ready for review

#93 #92 Login History(activities)
  app/dashboard/trainee/Attendance.tsx
  app/dashboard/trainee/LoginActivity.tsx
  app/dashboard/trainee/LoginActivitySkeleton.tsx
  components/ProfileDropdown.tsx
  components/sidebar.tsx
  graphql/queries/loginActivity.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
Labels: ready for review

#95 Real time notifications
  app/_layout.tsx
  app/dashboard/_layout.tsx
  app/dashboard/trainee/notifications.tsx
  graphql/client.ts
  graphql/mutations/notificationMutation.tsx
  hooks/useNotification.tsx
  package-lock.json
  package.json
Labels: ready for review

#114 #103 Full Screen Sidebar Implementation
  app/dashboard/_layout.tsx
  components/ProfileDropdown.tsx
  components/ProfileSidebar.tsx
  components/sidebar.tsx
Labels: ready for review

#122 Fix Language Picker Modal UI
  components/LanguagePicker.tsx
Labels: ready for review

#119 #101 fixes Trainee dashboard performance graph
  components/perfomanceStats/index.tsx
Labels: ready for review

#116 #94 Tickets page implementation
  app/dashboard/trainee/tickets.tsx
  assets/Icons/dashboard/Icons.tsx
  components/DataPaginations.tsx
  components/TicketsActions.tsx
  components/TicketsDetailsModal.tsx
  components/sidebar.tsx
  graphql/queries/tickets.queries.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
  package.json
Labels: ready for review

#121 #99 Improved Trainee Profile
  app.json
  app/dashboard/_layout.tsx
  app/dashboard/trainee/profile/edit.tsx
  app/dashboard/trainee/profile/index.tsx
  components/Login/OrgLogin.tsx
  components/ProfileAvatar.tsx
  constants/countries.ts
  graphql/mutations/updateAvatar.mutation.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
  package.json
Labels: ready for review

#125 Implement Dynamic Notification Navigation
  app/dashboard/trainee/notifications.tsx
Labels: feature

#120 Fix Preference Page Icons
  %ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
  app/auth/login/index.tsx
  app/auth/two-factor/index.tsx
  assets/Preference_icons/down_arrow.png
  assets/Preference_icons/forward-pref-icon.png
  assets/Preference_icons/index.d.ts
  assets/Preference_icons/preference_icons.ts
  components/Login/OrgLogin.tsx
  components/Login/UserLogin.tsx
  components/settingPreference/SettingPreference.tsx
  graphql/mutations/login.mutation.ts
  graphql/mutations/two-factor.mutation.ts
  graphql/queries/user.ts
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
Labels: ready for review
