Repository atlp-rwanda/atlp-pulse-mobile, pull requests merged in 2024-10, with the labels that each got.

#41 Dashboard layout & sidebar
  __tests__/components/sidebar.test.tsx
  app/_layout.tsx
  app/dashboard/_layout.tsx
  app/dashboard/index.tsx
  app/dashboard/trainee/index.tsx
  assets/Icons/auth/Icons.tsx
  assets/Icons/dashboard/Icons.tsx
  assets/images/profilePic.png
  components/sidebar.tsx
Labels: feature, ready for review

#37 #31 Setup App deployment and CI
  .github/workflows/publish.yml
  .gitignore
  eas.json
  package-lock.json
Labels: chore, ready for review

#45 ft(#4): Reset password
  __tests__/auth/login/UserLogin.test.tsx
  __tests__/forgetpassword/forgot-password.test.tsx
  __tests__/forgetpassword/reset-password.test.tsx
  app/(onboarding)/index.tsx
  app/_layout.tsx
  app/auth/forgot-password.tsx
  app/auth/login/index.tsx
  app/auth/reset-password.tsx
  components/Login/UserLogin.tsx
  components/icons/icons.ts
  package-lock.json
  package.json
  validations/login.schema.ts
Labels: feature, ready for review

#47 #44 Improve registration flow
  __tests__/components/sidebar.test.tsx
  app/(onboarding)/index.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/auth/register.tsx
  app/dashboard/_layout.tsx
  app/dashboard/index.tsx
  app/redirect.tsx
  assets/Icons/auth/Icons.tsx
  assets/Icons/dashboard/Icons.tsx
  assets/images/page_not_found.svg
  components/Login/UserLogin.tsx
  components/sidebar.tsx
  package-lock.json
  package.json
Labels: chore

#49 #43 Implement sprint rating & Recent feedback
  __tests__/components/TraineeRatings.test.tsx
  app/auth/login/index.tsx
  app/dashboard/_layout.tsx
  app/dashboard/index.tsx
  app/dashboard/trainee/attendance.tsx
  babel.config.js
  components/sidebar.tsx
  components/sprintRatings.tsx
  graphql/mutations/ratings.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: ready for review

#56 ft(frontend): implement Logout and fix navigation issues
  __tests__/auth/login/OrgLogin.test.tsx
  __tests__/components/sidebar.test.tsx
  app/auth/login/index.tsx
  app/dashboard/_layout.tsx
  app/dashboard/profile/orgInfo.tsx
  components/Login/OrgLogin.tsx
  components/sidebar.tsx
Labels: ready for review

#48 Perfomance stats for the trainee
  app/(onboarding)/index.tsx
  app/dashboard/index.tsx
  app/dashboard/perfomance/index.tsx
  components/perfomanceStats/circleIndicator.tsx
  components/perfomanceStats/index.tsx
  components/perfomanceStats/styles.tsx
  components/sidebar.tsx
  graphql/queries/rating.tsx
  package-lock.json
  package.json
Labels: ready for review

#54 Fix: select gender component
  __tests__/+not-found.test.tsx
  __tests__/auth/login/OrgLogin.test.tsx
  __tests__/dashboard/index.test.tsx
  __tests__/dashboard/trainee/index.test.tsx
  app/(onboarding)/index.tsx
  app/auth/login/index.tsx
  app/auth/register.tsx
  components/Login/UserLogin.tsx
  components/sidebar.tsx
  package-lock.json
  package.json
Labels: ready for review

#53 Fixing sprint rating and comment model
  app/dashboard/index.tsx
  components/feedbackModel.tsx
  components/perfomanceStats/index.tsx
  components/sprintRatings.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: ready for review

#58 Internationalize app to support more than one language
  __tests__/components/LanguagePicker.test.tsx
  app.json
  app/(onboarding)/index.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/auth/_layout.tsx
  app/auth/forgot-password.tsx
  app/auth/register.tsx
  app/dashboard/_layout.tsx
  app/redirect.tsx
  components/LanguagePicker.tsx
  components/Login/OrgLogin.tsx
  components/Login/UserLogin.tsx
  components/perfomanceStats/index.tsx
  components/sidebar.tsx
  components/sprintRatings.tsx
  components/trainee/About.tsx
  components/trainee/Organisation.tsx
  internationalization/index.ts
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
  package.json
  validations/login.schema.ts
  validations/register.schema.ts
Labels: ready for review

#59 #6 Updating trainee profile data
  app/dashboard/EditProfile/EditProfile.tsx
  app/dashboard/Resume/Resume.tsx
  app/dashboard/trainee/Profile.tsx
  constants/countries.ts
  graphql/mutations/Resume.mutations.tsx
  graphql/mutations/UpdateProfile.mutation.tsx
  graphql/queries/GetProfile.tsx
  package-lock.json
  package.json
  validations/editProfile.schema.ts
Labels: feature, ready for review

#57 #10 Account password reset
  AppManager.tsx
  __tests__/auth/login/OrgLogin.test.tsx
  __tests__/auth/login/UserLogin.test.tsx
  __tests__/components/About_trainee.test.tsx
  __tests__/components/LanguagePicker.test.tsx
  __tests__/components/TraineeRatings.test.tsx
  __tests__/components/Trainee_org.test.tsx
  __tests__/components/sidebar.test.tsx
  __tests__/dashboard/trainee/Profile.test.tsx
  app.json
  app/(onboarding)/index.tsx
  app/+not-found.tsx
  app/auth/_layout.tsx
  app/auth/forgot-password.tsx
  app/auth/login/index.tsx
  app/auth/register.tsx
  app/auth/reset-password.tsx
  app/dashboard/Resume/Resume.tsx
  app/dashboard/_layout.tsx
  app/dashboard/index.tsx
  app/dashboard/trainee/Profile.tsx
  assets/Icons/dashboard/Icons.tsx
  components/LanguagePicker.tsx
  components/Login/OrgLogin.tsx
  components/Login/UserLogin.tsx
  components/feedbackModel.tsx
  components/icons/icons.ts
  components/perfomanceStats/index.tsx
  components/profile/about.tsx
  components/sidebar.tsx
  components/sprintRatings.tsx
  components/trainee/About.tsx
  components/trainee/Account.tsx
  components/trainee/Organisation.tsx
  graphql/mutations/User.tsx
  graphql/mutations/changePassword.ts
  graphql/mutations/user.tsx
  graphql/queries/GetProfile.tsx
  graphql/queries/User.tsx
  internationalization/index.ts
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
  package.json
  tailwind.config.js
  tsconfig.json
  validations/changePassword.schema.ts
  validations/editProfile.schema.ts
  validations/login.schema.ts
  validations/register.schema.ts
Labels: feature, ready for review

#76 Fix Logout Issues
  components/sidebar.tsx
  package-lock.json
Labels: ready for review

#74 Fix Org Field Issues
  app/(onboarding)/index.tsx
  components/Login/OrgLogin.tsx
  components/Login/UserLogin.tsx
Labels: ready for review

#62 Chore: fix app inconsistencies
  .github/workflows/publish.yml
  DEPLOYMENT.md
  __tests__/auth/login/OrgLogin.test.tsx
  __tests__/dashboard/trainee/Profile.test.tsx
  app.json
  app/(onboarding)/_layout.tsx
  app/(onboarding)/index.tsx
  app/auth/_layout.tsx
  app/auth/forgot-password.tsx
  app/auth/login/index.tsx
  app/auth/register.tsx
  app/auth/reset-password.tsx
  app/dashboard/EditProfile/EditProfile.tsx
  app/dashboard/Resume/Resume.tsx
  app/dashboard/_layout.tsx
  app/dashboard/trainee/profile/edit.tsx
  app/dashboard/trainee/profile/index.tsx
  components/Login/OrgLogin.tsx
  components/Login/UserLogin.tsx
  components/ProfileAvatar.tsx
  components/feedbackModel.tsx
  components/perfomanceStats/index.tsx
  components/sidebar.tsx
  components/sprintRatings.tsx
  components/trainee/About.tsx
  components/trainee/Account.tsx
  components/trainee/Organisation.tsx
  constants/countries.ts
  graphql/mutations/user.tsx
  graphql/queries/GetProfile.tsx
  graphql/queries/user.ts
  hooks/useAuth.tsx
  internationalization/locales/en.json
  internationalization/locales/fr.json
  internationalization/locales/kin.json
  package-lock.json
  package.json
Labels: chore

#77 Upload and view trainee resume
  .env.example
  app/dashboard/Resume/Resume.tsx
  app/dashboard/trainee/profile/edit.tsx
  app/dashboard/trainee/profile/index.tsx
  babel.config.js
  components/Resume.tsx
  components/trainee/About.tsx
  graphql/queries/user.ts
  package-lock.json
  package.json
Labels: ready for review
